### ISSUE TITLE
Too large left margin for navigation icon on Lollipop

### ISSUE THREAD

**Issue by romanzes** [lurbas/ResponsiveToolbar#1]
Nice work, but as of Android 5.0.2, styles seem to be broken. Shows as intended on previous Android versions, though. Do you have any idea how to achieve the same effect on the latest SDK?

**Comment by lurbas** [comment]
Hi, 
thanks for contribution. I tested project sample on my OPO with 5.0.2 and it looks fine. Can you write more details? Phone, os version, some screenshots. What version of appcompat are you using? Project is built with 21.0.0, today I will test it on 21.1.1.

**Comment by lurbas** [comment]
I investigated it a little bit. Updated appcompat doesn't change anything. Only one thing I found was wrong width of navigation arrow in ActionMode. I fixed it with:

```sh
<style name="Custom.Widget.ActionButton.CloseMode" parent="Widget.AppCompat.ActionButton.CloseMode">
        ...
        <item name="android:minWidth">48dp</item>
</style>
```

Check if it solves your problem.
